name: Docker Build & Push

on:
  workflow_call:

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USER }}/employee-tracker-backend:${{ github.ref_name }}
            ${{ vars.DOCKERHUB_USER }}/employee-tracker-backend:latest
            ${{ vars.DOCKERHUB_USER }}/employee-tracker-backend:${{ github.sha}}

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USER }}/employee-tracker-frontend:${{ github.ref_name }}
            ${{ vars.DOCKERHUB_USER }}/employee-tracker-frontend:latest
            ${{ vars.DOCKERHUB_USER }}/employee-tracker-frontend:${{ github.sha}}